//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba_Entrevista.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Cliente
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Debe ingresar sus nombres")]
        [MaxLength(50, ErrorMessage = "El campo no puede tener más de 50 caracteres")]
        [RegularExpression("^[A-Za-z0-9 _]*[A-Za-z0-9][A-Za-z0-9 _]*$", ErrorMessage = "El nombre no puede contener caracteres especiales")]
        public string Nombres { get; set; }

        [Required(ErrorMessage = "Debe ingresar sus apellidos")]
        [MaxLength(50, ErrorMessage = "El campo no puede tener más de 50 caracteres")]
        [RegularExpression("^[A-Za-z0-9 _]*[A-Za-z0-9][A-Za-z0-9 _]*$", ErrorMessage = "El nombre no puede contener caracteres especiales")]
        public string Apellidos { get; set; }

        [Required(ErrorMessage = "Debe ingresar su número de identificación")]
        [MaxLength(15, ErrorMessage = "El campo no puede tener más de 15 caracteres")]
        [DisplayName("Identificación")]
        public string Identificacion { get; set; }

        [Required(ErrorMessage = "Debe ingresar una fecha válida")]
        [DisplayName("Fecha de nacimiento")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime FechaDeNacimiento { get; set; }
        public string Sexo { get; set; }
    }
}
